base: &base
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 

development:
  <<: *base
  database: bim_development

test: &test
  <<: *base
  database: bim_test

cucumber: